"""initial TANAW schema

Revision ID: 0001
Revises:
Create Date: 2026-07-19 22:22:12.715854
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TRIGGER_TABLES = (
    "accounts",
    "enterprise_profiles",
    "account_email_change_requests",
    "activity_logs",
    "email_outbox",
    "enterprise_telemetry_snapshots",
    "enterprise_report_submissions",
    "final_reports",
    "operational_alerts",
    "user_notifications",
    "support_tickets",
    "support_ticket_messages",
    "system_configuration",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("first_name", sa.String(length=60), nullable=True),
        sa.Column("last_name", sa.String(length=60), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("IT", "ADMIN", "STAFF", "ENTERPRISE", name="account_role"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", name="account_status"), nullable=False),
        sa.Column("is_protected_system_account", sa.Boolean(), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("token_invalid_before", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("preferences_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_email"), "accounts", ["email"], unique=True)
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("actor_role", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_id", sa.String(length=120), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_logs_actor_role"), "activity_logs", ["actor_role"], unique=False
    )
    op.create_index(op.f("ix_activity_logs_category"), "activity_logs", ["category"], unique=False)
    op.execute("CREATE SEQUENCE final_report_code_sequence START WITH 1")
    op.create_table(
        "final_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("report_code", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("period", sa.String(length=120), nullable=False),
        sa.Column(
            "generated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("prepared_by", sa.String(length=120), nullable=False),
        sa.Column("prepared_role", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("archived_from_status", sa.String(length=40), nullable=True),
        sa.Column("total_entry", sa.Integer(), nullable=False),
        sa.Column("total_exit", sa.Integer(), nullable=False),
        sa.Column("total_unique", sa.Integer(), nullable=False),
        sa.Column("enterprise_count", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_final_reports_generated_on"), "final_reports", ["generated_on"], unique=False
    )
    op.create_index(op.f("ix_final_reports_period"), "final_reports", ["period"], unique=False)
    op.create_index(
        op.f("ix_final_reports_report_code"), "final_reports", ["report_code"], unique=True
    )
    op.create_table(
        "operational_alerts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("alert_code", sa.String(length=40), nullable=False),
        sa.Column("alert_type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("enterprise", sa.String(length=120), nullable=True),
        sa.Column("requester", sa.String(length=120), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("required_action", sa.Text(), nullable=False),
        sa.Column("resolution_mode", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("owner", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_operational_alerts_alert_code"), "operational_alerts", ["alert_code"], unique=True
    )
    op.create_index(
        op.f("ix_operational_alerts_alert_type"), "operational_alerts", ["alert_type"], unique=False
    )
    op.create_index(
        op.f("ix_operational_alerts_created_at"), "operational_alerts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_operational_alerts_owner"), "operational_alerts", ["owner"], unique=False
    )
    op.create_index(
        op.f("ix_operational_alerts_severity"), "operational_alerts", ["severity"], unique=False
    )
    op.create_index(
        op.f("ix_operational_alerts_source_id"), "operational_alerts", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_operational_alerts_status"), "operational_alerts", ["status"], unique=False
    )
    op.create_table(
        "password_reset_rate_limit_buckets",
        sa.Column("bucket_key", sa.String(length=120), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scope IN ('global', 'ip', 'identifier')", name="ck_password_reset_rate_scope"
        ),
        sa.CheckConstraint("request_count >= 0", name="ck_password_reset_rate_count"),
        sa.PrimaryKeyConstraint("bucket_key"),
    )
    op.create_index(
        op.f("ix_password_reset_rate_limit_buckets_scope"),
        "password_reset_rate_limit_buckets",
        ["scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_rate_limit_buckets_updated_at"),
        "password_reset_rate_limit_buckets",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "system_configuration",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("values_json", sa.Text(), nullable=False),
        sa.Column("updated_by", sa.String(length=120), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "account_activation_tokens",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_account_activation_tokens_account_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_activation_tokens_account_id"),
        "account_activation_tokens",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_activation_tokens_expires_at"),
        "account_activation_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_activation_tokens_token_hash"),
        "account_activation_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "account_email_change_requests",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("old_email", sa.String(length=255), nullable=False),
        sa.Column("requested_email", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requested_by_account_id", sa.String(length=36), nullable=True),
        sa.Column("requested_by_name", sa.String(length=120), nullable=False),
        sa.Column("requested_by_role", sa.String(length=40), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_account_id", sa.String(length=36), nullable=True),
        sa.Column("resolved_by_name", sa.String(length=120), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending_verification', 'verified', 'approved', 'rejected', 'cancelled', 'replaced', 'expired')",
            name="ck_account_email_change_status",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_account_email_change_requests_account_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_account_id"],
            ["accounts.id"],
            name="fk_account_email_change_requests_requested_by_account_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_account_id"],
            ["accounts.id"],
            name="fk_account_email_change_requests_resolved_by_account_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_email_change_requests_account_id"),
        "account_email_change_requests",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_email_change_requests_expires_at"),
        "account_email_change_requests",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_email_change_requests_invalidated_at"),
        "account_email_change_requests",
        ["invalidated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_email_change_requests_requested_email"),
        "account_email_change_requests",
        ["requested_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_email_change_requests_status"),
        "account_email_change_requests",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_email_change_requests_token_hash"),
        "account_email_change_requests",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        "uq_account_email_change_active_account",
        "account_email_change_requests",
        ["account_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending_verification', 'verified')"),
        sqlite_where=sa.text("status IN ('pending_verification', 'verified')"),
    )
    op.create_index(
        "uq_account_email_change_active_email",
        "account_email_change_requests",
        ["requested_email"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending_verification', 'verified')"),
        sqlite_where=sa.text("status IN ('pending_verification', 'verified')"),
    )
    op.create_table(
        "email_outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("purpose", sa.String(length=60), nullable=False),
        sa.Column("source_id", sa.String(length=120), nullable=False),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column("sender", sa.String(length=255), nullable=False),
        sa.Column("template_name", sa.String(length=60), nullable=False),
        sa.Column("template_version", sa.String(length=20), nullable=False),
        sa.Column("secret_version", sa.String(length=20), nullable=False),
        sa.Column("template_payload_json", sa.Text(), nullable=False),
        sa.Column("tags_json", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=256), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lock_token", sa.String(length=36), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lock_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_message_id", sa.String(length=120), nullable=True),
        sa.Column("provider_payload_hash", sa.String(length=64), nullable=True),
        sa.Column("first_provider_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_provider_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome_uncertain", sa.Boolean(), nullable=False),
        sa.Column("manual_retry_count", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'processing' AND lock_token IS NOT NULL AND lock_expires_at IS NOT NULL) OR (status <> 'processing' AND lock_token IS NULL AND lock_expires_at IS NULL)",
            name="ck_email_outbox_lease_state",
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_email_outbox_attempt_count"),
        sa.CheckConstraint("manual_retry_count >= 0", name="ck_email_outbox_manual_retry_count"),
        sa.CheckConstraint("max_attempts >= 1", name="ck_email_outbox_max_attempts"),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name="fk_email_outbox_account_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "purpose", "source_id", "recipient", name="uq_email_outbox_logical_message"
        ),
    )
    op.create_index(
        op.f("ix_email_outbox_account_id"), "email_outbox", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_email_outbox_created_at"), "email_outbox", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_email_outbox_idempotency_key"), "email_outbox", ["idempotency_key"], unique=True
    )
    op.create_index(
        op.f("ix_email_outbox_lock_expires_at"), "email_outbox", ["lock_expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_email_outbox_next_attempt_at"), "email_outbox", ["next_attempt_at"], unique=False
    )
    op.create_index(
        op.f("ix_email_outbox_provider_message_id"),
        "email_outbox",
        ["provider_message_id"],
        unique=True,
    )
    op.create_index(op.f("ix_email_outbox_purpose"), "email_outbox", ["purpose"], unique=False)
    op.create_index(
        "ix_email_outbox_purpose_source", "email_outbox", ["purpose", "source_id"], unique=False
    )
    op.create_index(op.f("ix_email_outbox_source_id"), "email_outbox", ["source_id"], unique=False)
    op.create_index(op.f("ix_email_outbox_status"), "email_outbox", ["status"], unique=False)
    op.create_index(
        "ix_email_outbox_status_next_attempt",
        "email_outbox",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_table(
        "enterprise_profiles",
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("enterprise_id", sa.String(length=120), nullable=False),
        sa.Column("enterprise_name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("manager_name", sa.String(length=120), nullable=False),
        sa.Column("barangay", sa.String(length=120), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("location_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("building_capacity", sa.Integer(), nullable=False),
        sa.Column("gateway_id", sa.String(length=120), nullable=True),
        sa.Column("gateway_status", sa.String(length=40), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_enterprise_profiles_account_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_index(
        op.f("ix_enterprise_profiles_enterprise_id"),
        "enterprise_profiles",
        ["enterprise_id"],
        unique=True,
    )
    op.create_table(
        "password_reset_challenges",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=True),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("reset_attempts", sa.Integer(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("code_consumed", sa.Boolean(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("reset_token_hash", sa.String(length=64), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempts >= 0", name="ck_password_reset_challenge_attempts"),
        sa.CheckConstraint(
            "reset_attempts >= 0", name="ck_password_reset_challenge_reset_attempts"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_password_reset_challenges_account_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_challenges_account_id"),
        "password_reset_challenges",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_challenges_email"),
        "password_reset_challenges",
        ["email"],
        unique=False,
    )
    op.create_index(
        "ix_password_reset_challenges_email_active_created",
        "password_reset_challenges",
        ["email", "used", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_challenges_expires_at"),
        "password_reset_challenges",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_challenges_invalidated_at"),
        "password_reset_challenges",
        ["invalidated_at"],
        unique=False,
    )
    op.create_table(
        "user_notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recipient_account_id", sa.String(length=36), nullable=False),
        sa.Column("recipient_role", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("notification_type", sa.String(length=60), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=True),
        sa.Column("source_id", sa.String(length=120), nullable=True),
        sa.Column("created_by_account_id", sa.String(length=36), nullable=True),
        sa.Column("created_by_name", sa.String(length=120), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["accounts.id"],
            name="fk_user_notifications_created_by_account_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_account_id"],
            ["accounts.id"],
            name="fk_user_notifications_recipient_account_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_notifications_created_at"), "user_notifications", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_notifications_notification_type"),
        "user_notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_notifications_recipient_account_id"),
        "user_notifications",
        ["recipient_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_notifications_recipient_role"),
        "user_notifications",
        ["recipient_role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_notifications_severity"), "user_notifications", ["severity"], unique=False
    )
    op.create_index(
        op.f("ix_user_notifications_source_id"), "user_notifications", ["source_id"], unique=False
    )
    op.create_table(
        "email_delivery_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("outbox_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("provider_message_id", sa.String(length=120), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("outcome_uncertain", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["outbox_id"],
            ["email_outbox.id"],
            name="fk_email_delivery_attempts_outbox_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("outbox_id", "attempt_number", name="uq_email_delivery_attempt"),
    )
    op.create_index(
        op.f("ix_email_delivery_attempts_outbox_id"),
        "email_delivery_attempts",
        ["outbox_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_delivery_attempts_status"),
        "email_delivery_attempts",
        ["status"],
        unique=False,
    )
    op.create_table(
        "enterprise_report_submissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=80), nullable=False),
        sa.Column("enterprise_profile_id", sa.String(length=36), nullable=False),
        sa.Column("enterprise_name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("barangay", sa.String(length=120), nullable=True),
        sa.Column("period", sa.String(length=120), nullable=False),
        sa.Column("month", sa.String(length=40), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("entries", sa.Integer(), nullable=False),
        sa.Column("exits", sa.Integer(), nullable=False),
        sa.Column("peak_occupancy", sa.Integer(), nullable=False),
        sa.Column("unique_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("review_status", sa.String(length=40), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("sync_status", sa.String(length=60), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_profile_id"],
            ["enterprise_profiles.account_id"],
            name="fk_enterprise_report_submissions_enterprise_profile_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "enterprise_profile_id", "report_id", name="uq_enterprise_report_submission"
        ),
        sa.UniqueConstraint("enterprise_profile_id", "period", name="uq_enterprise_report_period"),
    )
    op.create_index(
        op.f("ix_enterprise_report_submissions_enterprise_profile_id"),
        "enterprise_report_submissions",
        ["enterprise_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enterprise_report_submissions_month"),
        "enterprise_report_submissions",
        ["month"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enterprise_report_submissions_period"),
        "enterprise_report_submissions",
        ["period"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enterprise_report_submissions_received_at"),
        "enterprise_report_submissions",
        ["received_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enterprise_report_submissions_report_id"),
        "enterprise_report_submissions",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enterprise_report_submissions_submitted_at"),
        "enterprise_report_submissions",
        ["submitted_at"],
        unique=False,
    )
    op.create_table(
        "report_submission_operations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("enterprise_profile_id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("report_id", sa.String(length=80), nullable=False),
        sa.Column("intake_report_id", sa.String(length=36), nullable=True),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["enterprise_profile_id"],
            ["enterprise_profiles.account_id"],
            name="fk_report_submission_operations_enterprise_profile_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["intake_report_id"],
            ["enterprise_report_submissions.id"],
            name="fk_report_submission_operations_intake_report_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "enterprise_profile_id",
            "submission_id",
            name="uq_report_submission_operation_identity",
        ),
    )
    op.create_index(
        op.f("ix_report_submission_operations_enterprise_profile_id"),
        "report_submission_operations",
        ["enterprise_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_submission_operations_intake_report_id"),
        "report_submission_operations",
        ["intake_report_id"],
        unique=False,
    )
    op.create_table(
        "enterprise_telemetry_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("enterprise_profile_id", sa.String(length=36), nullable=False),
        sa.Column("enterprise_name", sa.String(length=120), nullable=False),
        sa.Column("camera_id", sa.String(length=80), nullable=True),
        sa.Column("camera_name", sa.String(length=120), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("entries", sa.Integer(), nullable=False),
        sa.Column("exits", sa.Integer(), nullable=False),
        sa.Column("current_occupancy", sa.Integer(), nullable=False),
        sa.Column("peak_occupancy", sa.Integer(), nullable=False),
        sa.Column("unique_count", sa.Integer(), nullable=False),
        sa.Column("confirmed_unique_count", sa.Integer(), nullable=False),
        sa.Column("degraded_unique_count", sa.Integer(), nullable=False),
        sa.Column("total_events", sa.Integer(), nullable=False),
        sa.Column("unsubmitted_events", sa.Integer(), nullable=False),
        sa.Column("unsynced_events", sa.Integer(), nullable=False),
        sa.Column("running", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("analytics_fps", sa.Float(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["enterprise_profile_id"],
            ["enterprise_profiles.account_id"],
            name="fk_enterprise_telemetry_snapshots_enterprise_profile_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_enterprise_telemetry_snapshots_captured_at"),
        "enterprise_telemetry_snapshots",
        ["captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enterprise_telemetry_snapshots_enterprise_profile_id"),
        "enterprise_telemetry_snapshots",
        ["enterprise_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enterprise_telemetry_snapshots_received_at"),
        "enterprise_telemetry_snapshots",
        ["received_at"],
        unique=False,
    )
    op.create_table(
        "support_tickets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_code", sa.String(length=40), nullable=False),
        sa.Column("enterprise_profile_id", sa.String(length=36), nullable=False),
        sa.Column("enterprise_name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("affected_area", sa.String(length=120), nullable=True),
        sa.Column("camera_node", sa.String(length=120), nullable=True),
        sa.Column("attachments_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_profile_id"],
            ["enterprise_profiles.account_id"],
            name="fk_support_tickets_enterprise_profile_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_support_tickets_category"), "support_tickets", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_support_tickets_created_at"), "support_tickets", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_support_tickets_enterprise_profile_id"),
        "support_tickets",
        ["enterprise_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_support_tickets_priority"), "support_tickets", ["priority"], unique=False
    )
    op.create_index(op.f("ix_support_tickets_status"), "support_tickets", ["status"], unique=False)
    op.create_index(
        op.f("ix_support_tickets_ticket_code"), "support_tickets", ["ticket_code"], unique=True
    )
    op.create_table(
        "final_report_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("final_report_id", sa.String(length=36), nullable=False),
        sa.Column("intake_report_id", sa.String(length=36), nullable=False),
        sa.Column("enterprise", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("unique_count", sa.Integer(), nullable=False),
        sa.Column("entries", sa.Integer(), nullable=False),
        sa.Column("exits", sa.Integer(), nullable=False),
        sa.Column("this_prov_male", sa.Integer(), nullable=True),
        sa.Column("this_prov_female", sa.Integer(), nullable=True),
        sa.Column("other_prov_male", sa.Integer(), nullable=True),
        sa.Column("other_prov_female", sa.Integer(), nullable=True),
        sa.Column("foreign_male", sa.Integer(), nullable=True),
        sa.Column("foreign_female", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["final_report_id"],
            ["final_reports.id"],
            name="fk_final_report_sources_final_report_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["intake_report_id"],
            ["enterprise_report_submissions.id"],
            name="fk_final_report_sources_intake_report_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intake_report_id", name="uq_final_report_source_intake"),
    )
    op.create_index(
        op.f("ix_final_report_sources_final_report_id"),
        "final_report_sources",
        ["final_report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_final_report_sources_intake_report_id"),
        "final_report_sources",
        ["intake_report_id"],
        unique=False,
    )
    op.create_table(
        "support_ticket_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("author_account_id", sa.String(length=36), nullable=False),
        sa.Column("author_name", sa.String(length=120), nullable=False),
        sa.Column("author_role", sa.String(length=40), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_account_id"],
            ["accounts.id"],
            name="fk_support_ticket_messages_author_account_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["support_tickets.id"],
            name="fk_support_ticket_messages_ticket_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_support_ticket_messages_author_account_id"),
        "support_ticket_messages",
        ["author_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_support_ticket_messages_created_at"),
        "support_ticket_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_support_ticket_messages_ticket_id"),
        "support_ticket_messages",
        ["ticket_id"],
        unique=False,
    )
    op.create_table(
        "realtime_outbox",
        sa.Column("sequence", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "event_id",
            sa.String(length=36),
            server_default=sa.text("gen_random_uuid()::text"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "scope",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "actor",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "audience_roles",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("coalesce_key", sa.String(length=160), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("sequence"),
        sa.UniqueConstraint("event_id", name="uq_realtime_outbox_event_id"),
        sa.CheckConstraint("schema_version = 1", name="ck_realtime_outbox_schema_version"),
        sa.CheckConstraint("attempt_count >= 0", name="ck_realtime_outbox_attempt_count"),
    )
    op.create_index(
        "ix_realtime_outbox_pending",
        "realtime_outbox",
        ["published_at", "sequence"],
        unique=False,
    )
    op.create_index(
        "uq_realtime_outbox_pending_coalesce",
        "realtime_outbox",
        ["coalesce_key"],
        unique=True,
        postgresql_where=sa.text("published_at IS NULL AND coalesce_key IS NOT NULL"),
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION tanaw_capture_realtime_event()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            event_type_value text;
            scope_value jsonb := '{}'::jsonb;
            actor_value jsonb := NULL;
            payload_value jsonb := '{}'::jsonb;
            audience_value jsonb := '[]'::jsonb;
            coalesce_value text := NULL;
            ticket_enterprise_account_id text;
            ticket_priority text;
        BEGIN
            IF TG_TABLE_NAME = 'support_tickets' THEN
                IF TG_OP = 'INSERT' THEN
                    event_type_value := 'support_ticket.created';
                ELSIF OLD.status IS DISTINCT FROM NEW.status THEN
                    event_type_value := 'support_ticket.status.changed';
                ELSE
                    event_type_value := 'support_ticket.updated';
                END IF;
                scope_value := jsonb_build_object(
                    'enterprise_account_id', NEW.enterprise_profile_id,
                    'ticket_id', NEW.id
                );
                payload_value := jsonb_build_object(
                    'ticket_id', NEW.id,
                    'status', NEW.status,
                    'priority', NEW.priority,
                    'updated_at', NEW.updated_at
                );
                audience_value := '["admin","it","enterprise"]'::jsonb;

            ELSIF TG_TABLE_NAME = 'support_ticket_messages' THEN
                SELECT enterprise_profile_id, priority
                  INTO ticket_enterprise_account_id, ticket_priority
                  FROM support_tickets
                 WHERE id = NEW.ticket_id;
                event_type_value := 'support_ticket.message.created';
                scope_value := jsonb_build_object(
                    'enterprise_account_id', ticket_enterprise_account_id,
                    'ticket_id', NEW.ticket_id
                );
                actor_value := jsonb_build_object(
                    'user_id', NEW.author_account_id,
                    'role', NEW.author_role
                );
                payload_value := jsonb_build_object(
                    'message_id', NEW.id,
                    'ticket_id', NEW.ticket_id,
                    'author_id', NEW.author_account_id,
                    'author_name', NEW.author_name,
                    'author_role', NEW.author_role,
                    'ticket_priority', ticket_priority,
                    'created_at', NEW.created_at
                );
                audience_value := '["admin","it","enterprise"]'::jsonb;

            ELSIF TG_TABLE_NAME = 'user_notifications' THEN
                event_type_value := CASE
                    WHEN TG_OP = 'INSERT' THEN 'notification.created'
                    ELSE 'notification.updated'
                END;
                scope_value := jsonb_build_object(
                    'recipient_account_id', NEW.recipient_account_id
                );
                actor_value := CASE
                    WHEN NEW.created_by_account_id IS NULL THEN NULL
                    ELSE jsonb_build_object('user_id', NEW.created_by_account_id)
                END;
                payload_value := jsonb_build_object(
                    'notification_id', NEW.id,
                    'recipient_role', NEW.recipient_role,
                    'source_type', NEW.source_type,
                    'source_id', NEW.source_id,
                    'read_at', NEW.read_at,
                    'created_at', NEW.created_at
                );
                audience_value := jsonb_build_array(NEW.recipient_role);

            ELSIF TG_TABLE_NAME = 'operational_alerts' THEN
                IF TG_OP = 'INSERT' THEN
                    event_type_value := 'alert.created';
                ELSIF OLD.status IS DISTINCT FROM NEW.status AND NEW.status = 'Resolved' THEN
                    event_type_value := 'alert.resolved';
                ELSIF OLD.status IS DISTINCT FROM NEW.status AND OLD.status = 'Resolved' THEN
                    event_type_value := 'alert.reopened';
                ELSIF OLD.status IS DISTINCT FROM NEW.status THEN
                    event_type_value := 'alert.status.changed';
                ELSE
                    event_type_value := 'alert.updated';
                END IF;
                payload_value := jsonb_build_object(
                    'alert_id', NEW.id,
                    'owner', NEW.owner,
                    'severity', NEW.severity,
                    'status', NEW.status,
                    'updated_at', NEW.updated_at
                );
                audience_value := CASE NEW.owner
                    WHEN 'Admin' THEN '["admin"]'::jsonb
                    WHEN 'IT' THEN '["it"]'::jsonb
                    ELSE '["admin","it"]'::jsonb
                END;

            ELSIF TG_TABLE_NAME = 'account_email_change_requests' THEN
                IF TG_OP = 'INSERT' THEN
                    event_type_value := 'account_request.created';
                ELSIF NEW.status = 'approved' THEN
                    event_type_value := 'account_request.approved';
                ELSIF NEW.status IN ('rejected', 'cancelled', 'expired', 'replaced') THEN
                    event_type_value := 'account_request.declined';
                ELSE
                    event_type_value := 'account_request.updated';
                END IF;
                scope_value := jsonb_build_object('recipient_account_id', NEW.account_id);
                actor_value := CASE
                    WHEN NEW.resolved_by_account_id IS NULL THEN
                        jsonb_build_object(
                            'user_id', NEW.requested_by_account_id,
                            'role', NEW.requested_by_role
                        )
                    ELSE jsonb_build_object('user_id', NEW.resolved_by_account_id)
                END;
                payload_value := jsonb_build_object(
                    'request_id', NEW.id,
                    'account_id', NEW.account_id,
                    'status', NEW.status,
                    'updated_at', NEW.updated_at
                );
                audience_value := '["it","enterprise"]'::jsonb;

            ELSIF TG_TABLE_NAME = 'accounts' THEN
                IF TG_OP = 'INSERT' THEN
                    event_type_value := 'user.created';
                ELSIF OLD.status IS DISTINCT FROM NEW.status THEN
                    event_type_value := 'user.status.changed';
                ELSE
                    event_type_value := 'user.updated';
                END IF;
                scope_value := jsonb_build_object('recipient_account_id', NEW.id);
                payload_value := jsonb_build_object(
                    'account_id', NEW.id,
                    'role', lower(NEW.role::text),
                    'status', lower(NEW.status::text),
                    'activated', NEW.activated_at IS NOT NULL,
                    'updated_at', NEW.updated_at
                );
                audience_value := CASE
                    WHEN NEW.role = 'ENTERPRISE' THEN '["it","admin","enterprise"]'::jsonb
                    ELSE '["it"]'::jsonb
                END;

            ELSIF TG_TABLE_NAME = 'enterprise_profiles' THEN
                event_type_value := CASE
                    WHEN TG_OP = 'INSERT' THEN 'enterprise.created'
                    ELSE 'enterprise.updated'
                END;
                scope_value := jsonb_build_object(
                    'recipient_account_id', NEW.account_id,
                    'enterprise_account_id', NEW.account_id,
                    'enterprise_id', NEW.enterprise_id
                );
                payload_value := jsonb_build_object(
                    'account_id', NEW.account_id,
                    'enterprise_id', NEW.enterprise_id,
                    'gateway_status', NEW.gateway_status,
                    'updated_at', NEW.updated_at
                );
                audience_value := '["it","admin","enterprise"]'::jsonb;

            ELSIF TG_TABLE_NAME = 'activity_logs' THEN
                event_type_value := 'activity.created';
                payload_value := jsonb_build_object(
                    'activity_id', NEW.id,
                    'category', NEW.category,
                    'severity', NEW.severity,
                    'actor_role', NEW.actor_role,
                    'action', NEW.action,
                    'source_id', NEW.source_id,
                    'timestamp', NEW.timestamp
                );
                audience_value := '["admin","it"]'::jsonb;

            ELSIF TG_TABLE_NAME = 'enterprise_report_submissions' THEN
                IF TG_OP = 'INSERT' THEN
                    event_type_value := 'report.created';
                ELSIF NEW.status ILIKE '%fail%' OR NEW.review_status ILIKE '%reject%' THEN
                    event_type_value := 'report.failed';
                ELSIF NEW.status ILIKE '%final%' OR NEW.review_status = 'Consolidated' THEN
                    event_type_value := 'report.finalized';
                ELSIF NEW.status ILIKE '%process%' THEN
                    event_type_value := 'report.processing';
                ELSE
                    event_type_value := 'report.updated';
                END IF;
                scope_value := jsonb_build_object(
                    'enterprise_account_id', NEW.enterprise_profile_id,
                    'report_id', NEW.id
                );
                payload_value := jsonb_build_object(
                    'report_id', NEW.id,
                    'status', NEW.status,
                    'review_status', NEW.review_status,
                    'updated_at', NEW.updated_at
                );
                audience_value := '["admin","staff","enterprise"]'::jsonb;

            ELSIF TG_TABLE_NAME = 'final_reports' THEN
                IF TG_OP = 'INSERT' THEN
                    event_type_value := 'report.created';
                ELSIF NEW.status = 'Archived' THEN
                    event_type_value := 'report.archived';
                ELSIF NEW.status IN ('Finalized', 'Approved') THEN
                    event_type_value := 'report.finalized';
                ELSIF NEW.status ILIKE '%fail%' OR NEW.status ILIKE '%reject%' THEN
                    event_type_value := 'report.failed';
                ELSE
                    event_type_value := 'report.updated';
                END IF;
                scope_value := jsonb_build_object('report_id', NEW.id);
                payload_value := jsonb_build_object(
                    'report_id', NEW.id,
                    'status', NEW.status,
                    'updated_at', NEW.updated_at
                );
                audience_value := '["admin","staff"]'::jsonb;

            ELSIF TG_TABLE_NAME = 'email_outbox' THEN
                event_type_value := CASE
                    WHEN NEW.provider = 'local' AND NEW.status = 'recorded' THEN 'dev_log.created'
                    ELSE 'email_delivery.updated'
                END;
                scope_value := CASE
                    WHEN NEW.account_id IS NULL THEN '{}'::jsonb
                    ELSE jsonb_build_object('recipient_account_id', NEW.account_id)
                END;
                payload_value := jsonb_build_object(
                    'delivery_id', NEW.id,
                    'status', NEW.status,
                    'purpose', NEW.purpose,
                    'updated_at', NEW.updated_at
                );
                audience_value := '["it"]'::jsonb;

            ELSIF TG_TABLE_NAME = 'enterprise_telemetry_snapshots' THEN
                event_type_value := 'telemetry.updated';
                scope_value := jsonb_build_object(
                    'enterprise_account_id', NEW.enterprise_profile_id
                );
                payload_value := jsonb_build_object(
                    'snapshot_id', NEW.id,
                    'enterprise_account_id', NEW.enterprise_profile_id,
                    'received_at', NEW.received_at
                );
                audience_value := '["admin","it","staff","enterprise"]'::jsonb;
                coalesce_value := 'telemetry:' || NEW.enterprise_profile_id;

            ELSIF TG_TABLE_NAME = 'system_configuration' THEN
                event_type_value := 'system_setting.updated';
                payload_value := jsonb_build_object(
                    'configuration_id', NEW.id,
                    'updated_at', NEW.updated_at
                );
                audience_value := '["admin","it","staff","enterprise"]'::jsonb;
            ELSE
                RETURN NEW;
            END IF;

            IF coalesce_value IS NULL THEN
                INSERT INTO realtime_outbox (
                    event_type, scope, actor, payload, audience_roles
                ) VALUES (
                    event_type_value, scope_value, actor_value, payload_value, audience_value
                );
            ELSE
                INSERT INTO realtime_outbox (
                    event_type, scope, actor, payload, audience_roles, coalesce_key
                ) VALUES (
                    event_type_value,
                    scope_value,
                    actor_value,
                    payload_value,
                    audience_value,
                    coalesce_value
                )
                ON CONFLICT (coalesce_key)
                    WHERE published_at IS NULL AND coalesce_key IS NOT NULL
                DO UPDATE SET
                    occurred_at = now(),
                    scope = EXCLUDED.scope,
                    actor = EXCLUDED.actor,
                    payload = EXCLUDED.payload,
                    audience_roles = EXCLUDED.audience_roles;
            END IF;
            RETURN NEW;
        END;
        $$;
        """
    )

    for table_name in TRIGGER_TABLES:
        operations = "INSERT OR UPDATE" if table_name != "support_ticket_messages" else "INSERT"
        op.execute(
            f"""
            CREATE TRIGGER trg_{table_name}_realtime
            AFTER {operations} ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION tanaw_capture_realtime_event();
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in reversed(TRIGGER_TABLES):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_realtime ON {table_name};")
    op.execute("DROP FUNCTION IF EXISTS tanaw_capture_realtime_event();")
    op.drop_index(
        "uq_realtime_outbox_pending_coalesce",
        table_name="realtime_outbox",
        postgresql_where=sa.text("published_at IS NULL AND coalesce_key IS NOT NULL"),
    )
    op.drop_index("ix_realtime_outbox_pending", table_name="realtime_outbox")
    op.drop_table("realtime_outbox")
    op.drop_index(
        op.f("ix_support_ticket_messages_ticket_id"), table_name="support_ticket_messages"
    )
    op.drop_index(
        op.f("ix_support_ticket_messages_created_at"), table_name="support_ticket_messages"
    )
    op.drop_index(
        op.f("ix_support_ticket_messages_author_account_id"), table_name="support_ticket_messages"
    )
    op.drop_table("support_ticket_messages")
    op.drop_index(
        op.f("ix_final_report_sources_intake_report_id"), table_name="final_report_sources"
    )
    op.drop_index(
        op.f("ix_final_report_sources_final_report_id"), table_name="final_report_sources"
    )
    op.drop_table("final_report_sources")
    op.drop_index(op.f("ix_support_tickets_ticket_code"), table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_status"), table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_priority"), table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_enterprise_profile_id"), table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_created_at"), table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_category"), table_name="support_tickets")
    op.drop_table("support_tickets")
    op.drop_index(
        op.f("ix_enterprise_telemetry_snapshots_received_at"),
        table_name="enterprise_telemetry_snapshots",
    )
    op.drop_index(
        op.f("ix_enterprise_telemetry_snapshots_enterprise_profile_id"),
        table_name="enterprise_telemetry_snapshots",
    )
    op.drop_index(
        op.f("ix_enterprise_telemetry_snapshots_captured_at"),
        table_name="enterprise_telemetry_snapshots",
    )
    op.drop_table("enterprise_telemetry_snapshots")
    op.drop_index(
        op.f("ix_report_submission_operations_intake_report_id"),
        table_name="report_submission_operations",
    )
    op.drop_index(
        op.f("ix_report_submission_operations_enterprise_profile_id"),
        table_name="report_submission_operations",
    )
    op.drop_table("report_submission_operations")
    op.drop_index(
        op.f("ix_enterprise_report_submissions_submitted_at"),
        table_name="enterprise_report_submissions",
    )
    op.drop_index(
        op.f("ix_enterprise_report_submissions_report_id"),
        table_name="enterprise_report_submissions",
    )
    op.drop_index(
        op.f("ix_enterprise_report_submissions_received_at"),
        table_name="enterprise_report_submissions",
    )
    op.drop_index(
        op.f("ix_enterprise_report_submissions_period"), table_name="enterprise_report_submissions"
    )
    op.drop_index(
        op.f("ix_enterprise_report_submissions_month"), table_name="enterprise_report_submissions"
    )
    op.drop_index(
        op.f("ix_enterprise_report_submissions_enterprise_profile_id"),
        table_name="enterprise_report_submissions",
    )
    op.drop_table("enterprise_report_submissions")
    op.drop_index(op.f("ix_email_delivery_attempts_status"), table_name="email_delivery_attempts")
    op.drop_index(
        op.f("ix_email_delivery_attempts_outbox_id"), table_name="email_delivery_attempts"
    )
    op.drop_table("email_delivery_attempts")
    op.drop_index(op.f("ix_user_notifications_source_id"), table_name="user_notifications")
    op.drop_index(op.f("ix_user_notifications_severity"), table_name="user_notifications")
    op.drop_index(op.f("ix_user_notifications_recipient_role"), table_name="user_notifications")
    op.drop_index(
        op.f("ix_user_notifications_recipient_account_id"), table_name="user_notifications"
    )
    op.drop_index(op.f("ix_user_notifications_notification_type"), table_name="user_notifications")
    op.drop_index(op.f("ix_user_notifications_created_at"), table_name="user_notifications")
    op.drop_table("user_notifications")
    op.drop_index(
        op.f("ix_password_reset_challenges_invalidated_at"), table_name="password_reset_challenges"
    )
    op.drop_index(
        op.f("ix_password_reset_challenges_expires_at"), table_name="password_reset_challenges"
    )
    op.drop_index(
        "ix_password_reset_challenges_email_active_created", table_name="password_reset_challenges"
    )
    op.drop_index(
        op.f("ix_password_reset_challenges_email"), table_name="password_reset_challenges"
    )
    op.drop_index(
        op.f("ix_password_reset_challenges_account_id"), table_name="password_reset_challenges"
    )
    op.drop_table("password_reset_challenges")
    op.drop_index(op.f("ix_enterprise_profiles_enterprise_id"), table_name="enterprise_profiles")
    op.drop_table("enterprise_profiles")
    op.drop_index("ix_email_outbox_status_next_attempt", table_name="email_outbox")
    op.drop_index(op.f("ix_email_outbox_status"), table_name="email_outbox")
    op.drop_index(op.f("ix_email_outbox_source_id"), table_name="email_outbox")
    op.drop_index("ix_email_outbox_purpose_source", table_name="email_outbox")
    op.drop_index(op.f("ix_email_outbox_purpose"), table_name="email_outbox")
    op.drop_index(op.f("ix_email_outbox_provider_message_id"), table_name="email_outbox")
    op.drop_index(op.f("ix_email_outbox_next_attempt_at"), table_name="email_outbox")
    op.drop_index(op.f("ix_email_outbox_lock_expires_at"), table_name="email_outbox")
    op.drop_index(op.f("ix_email_outbox_idempotency_key"), table_name="email_outbox")
    op.drop_index(op.f("ix_email_outbox_created_at"), table_name="email_outbox")
    op.drop_index(op.f("ix_email_outbox_account_id"), table_name="email_outbox")
    op.drop_table("email_outbox")
    op.drop_index(
        "uq_account_email_change_active_email",
        table_name="account_email_change_requests",
        postgresql_where=sa.text("status IN ('pending_verification', 'verified')"),
        sqlite_where=sa.text("status IN ('pending_verification', 'verified')"),
    )
    op.drop_index(
        "uq_account_email_change_active_account",
        table_name="account_email_change_requests",
        postgresql_where=sa.text("status IN ('pending_verification', 'verified')"),
        sqlite_where=sa.text("status IN ('pending_verification', 'verified')"),
    )
    op.drop_index(
        op.f("ix_account_email_change_requests_token_hash"),
        table_name="account_email_change_requests",
    )
    op.drop_index(
        op.f("ix_account_email_change_requests_status"), table_name="account_email_change_requests"
    )
    op.drop_index(
        op.f("ix_account_email_change_requests_requested_email"),
        table_name="account_email_change_requests",
    )
    op.drop_index(
        op.f("ix_account_email_change_requests_invalidated_at"),
        table_name="account_email_change_requests",
    )
    op.drop_index(
        op.f("ix_account_email_change_requests_expires_at"),
        table_name="account_email_change_requests",
    )
    op.drop_index(
        op.f("ix_account_email_change_requests_account_id"),
        table_name="account_email_change_requests",
    )
    op.drop_table("account_email_change_requests")
    op.drop_index(
        op.f("ix_account_activation_tokens_token_hash"), table_name="account_activation_tokens"
    )
    op.drop_index(
        op.f("ix_account_activation_tokens_expires_at"), table_name="account_activation_tokens"
    )
    op.drop_index(
        op.f("ix_account_activation_tokens_account_id"), table_name="account_activation_tokens"
    )
    op.drop_table("account_activation_tokens")
    op.drop_table("system_configuration")
    op.drop_index(
        op.f("ix_password_reset_rate_limit_buckets_updated_at"),
        table_name="password_reset_rate_limit_buckets",
    )
    op.drop_index(
        op.f("ix_password_reset_rate_limit_buckets_scope"),
        table_name="password_reset_rate_limit_buckets",
    )
    op.drop_table("password_reset_rate_limit_buckets")
    op.drop_index(op.f("ix_operational_alerts_status"), table_name="operational_alerts")
    op.drop_index(op.f("ix_operational_alerts_source_id"), table_name="operational_alerts")
    op.drop_index(op.f("ix_operational_alerts_severity"), table_name="operational_alerts")
    op.drop_index(op.f("ix_operational_alerts_owner"), table_name="operational_alerts")
    op.drop_index(op.f("ix_operational_alerts_created_at"), table_name="operational_alerts")
    op.drop_index(op.f("ix_operational_alerts_alert_type"), table_name="operational_alerts")
    op.drop_index(op.f("ix_operational_alerts_alert_code"), table_name="operational_alerts")
    op.drop_table("operational_alerts")
    op.drop_index(op.f("ix_final_reports_report_code"), table_name="final_reports")
    op.drop_index(op.f("ix_final_reports_period"), table_name="final_reports")
    op.drop_index(op.f("ix_final_reports_generated_on"), table_name="final_reports")
    op.drop_table("final_reports")
    op.execute("DROP SEQUENCE final_report_code_sequence")
    op.drop_index(op.f("ix_activity_logs_category"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_actor_role"), table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_index(op.f("ix_accounts_email"), table_name="accounts")
    op.drop_table("accounts")
    op.execute("DROP TYPE IF EXISTS account_status")
    op.execute("DROP TYPE IF EXISTS account_role")
    # ### end Alembic commands ###
