export const routes = {
  home: "/",
  login: "/login",
  changePassword: "/change-password",
  enterpriseAccess: "/enterprise-access",
  it: {
    root: "/it",
    dashboard: "/it/dashboard",
    lguAccounts: "/it/lgu-accounts",
    enterpriseAccounts: "/it/enterprise-accounts",
    alerts: "/it/alerts",
    supportTickets: "/it/support-tickets",
    systemLogs: "/it/system-logs",
    devLog: "/it/dev-log",
    systemSettings: "/it/system-settings",
    profile: "/it/profile",
    security: "/it/security",
  },
  admin: {
    root: "/admin",
    mapview: "/admin/mapview",
    enterpriseRequests: "/admin/enterprise-requests",
    systemLogs: "/admin/system-logs",
    alertsMonitor: "/admin/alerts-monitor",
    supportTickets: "/admin/support-tickets",
    profile: "/admin/profile",
    security: "/admin/security",
  },
  staff: {
    root: "/staff",
    batchReports: "/staff/batch-reports",
    finalReportsAudit: "/staff/final-reports-audit",
    analytics: "/staff/analytics",
    systemLogs: "/staff/system-logs",
    profile: "/staff/profile",
    security: "/staff/security",
  },
} as const;
